name: Full Stack CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build and test backend services
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [HealthCareService, service-2, service-3]  # Backend services

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to your Node.js version

      - name: Install dependencies and run tests for ${{ matrix.service }}
        working-directory: ./backend/${{ matrix.service }}
        run: |
          npm install
          npm test

      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ./backend/${{ matrix.service }}
        run: |
          docker build -t my-backend-${{ matrix.service }} .

  # Job to build and test the frontend
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to your Node.js version

      - name: Install frontend dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Build Docker image for frontend
        working-directory: ./frontend
        run: |
          docker build -t my-frontend .

  # Job to deploy (you can add specific deployment steps here)
  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub (or your registry)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker images
        run: |
          docker tag my-backend-HealthCareService my-docker-repo/my-backend-HealthCareService:latest
          docker push my-docker-repo/my-backend-HealthCareService:latest
          docker tag my-backend-service-2 my-docker-repo/my-backend-service-2:latest
          docker push my-docker-repo/my-backend-service-2:latest
          docker tag my-backend-service-3 my-docker-repo/my-backend-service-3:latest
          docker push my-docker-repo/my-backend-service-3:latest

      - name: Push Frontend Docker image
        run: |
          docker tag my-frontend my-docker-repo/my-frontend:latest
          docker push my-docker-repo/my-frontend:latest
